CACHE_DIR = "data/cache"
OUTPUT_DIR = "data/output"
PLOTS_DIR = OUTPUT_DIR + "/plots"
MODELS_DIR = OUTPUT_DIR + "/models"
CACHED_DF_FILE_PATH = CACHE_DIR + "/cachedDF.csv"
FINAL_DF_FILE_PATH = OUTPUT_DIR + "/finalDF.csv"
RESULTS_FILE_PATH = OUTPUT_DIR + "/results.json"
